---
- name: Generating dev.yml for keystone
  template:
    src: services/openstack/keystone/dev.yml.j2
    dest: services/openstack/keystone/dev.yml

- name: Generating Dockerfile for keystone
  template:
    src: services/openstack/keystone/Dockerfile.j2
    dest: services/openstack/keystone/Dockerfile

- name: Generating start.sh for keystone
  template:
    src: services/openstack/keystone/start.sh.j2
    dest: services/openstack/keystone/start.sh

- name: Generating config.json for keystone
  template:
    src: services/openstack/keystone/config/config.json.j2
    dest: services/openstack/keystone/config/config.json
