---
  version: "3"

  services:

    opendaylight:
      build: .
      container_name: openstack_opendaylight
      networks:
        - openstack-management-net
      ports:
        - "0.0.0.0:8181:8181"
        - "0.0.0.0:8101:8101"
        - "0.0.0.0:6633:6633"
        - "0.0.0.0:6653:6653"
        - "0.0.0.0:2400:2400"
      external_links:
        - openstack_neutron:openstack_neutron
      command: ["bash", "start.sh"]

  networks:
    openstack-management-net:
      external: true
