---
  version: "3"

  services:

    nova_qemu:
      build: .
      container_name: openstack_nova_qemu
      networks:
        - openstack-management-net
      ports:
        - "0.0.0.0:8775:8775"
      external_links:
        - openstack_postgresql:openstack_postgresql
        - openstack_rabbitmq:openstack_rabbitmq
        - openstack_memcached:openstack_memcached
        - openstack_keystone:openstack_keystone
        - openstack_glance:openstack_glance
        - openstack_nova:openstack_nova
      volumes:
        - nova_log:/var/log/nova
        # - glance_etc:/etc/glance
      command: ["bash", "start.sh"]
  
  volumes:
    nova_log:
      driver: local
    # glance_etc:
      # driver: local
  
  networks:
    openstack-management-net:
      external: true
  