---
version: "3"

services:

  kibana:
    build: .
    container_name: openstack_infra_kibana
    ports:
      - "0.0.0.0:5601:5601"
    networks:
      - openstack-management-net
    environment:
      - "XPACK_MONITORING_ENABLED=false"
      - "XPACK_SECURITY_ENABLED=false"
      - "XPACK_MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED=false"
      - "xpack.ml.enabled=false"

networks:
  openstack-management-net:
    external: true
