---
version: "3"

services:

  glance:
    build: .
    container_name: openstack_glance
    networks:
      - openstack-management-net
    ports:
      - "0.0.0.0:9191:9191"
      - "0.0.0.0:9292:9292"
    external_links:
      - openstack_mariadb:openstack_mariadb
      - openstack_memcached:openstack_memcached
      - openstack_keystone:openstack_keystone
    volumes:
      - glance_log:/var/log/glance
      - glance_lib:/var/lib/glance
    command: ["bash", "start.sh"]

volumes:
  glance_log:
    driver: local
  glance_lib:
    driver: local

networks:
  openstack-management-net:
    external: true
