FROM openstack/seed:latest

LABEL maintainer=root@memogarcia.mx

RUN wget https://raw.githubusercontent.com/openstack/requirements/{{openstack_branch}}/upper-constraints.txt -O /opt/upper-constraints.txt && \
    mkdir /etc/glance && \
    git clone -b {{openstack_branch}} --depth=1 {{openstack_repo}}/glance.git /opt/glance

WORKDIR /opt/glance

RUN pip2 install -c /opt/upper-constraints.txt -e . && tox -e genconfig

VOLUME ["/var/log/glance", "/var/lib/glance", "/etc/cinder", "/opt"]

EXPOSE 9292 9191

COPY start.sh /opt/start.sh

COPY supervisord.conf /etc/supervisord.conf

COPY config/ /opt/config/

CMD ["bash", "/opt/start.sh"]
