---
version: "3"

services:

  nova:
    build: .
    container_name: openstack_nova
    networks:
      - openstack-management-net
    ports:
      - "0.0.0.0:8774:8774"
      - "0.0.0.0:8778:8778"
      - "0.0.0.0:6080:6080"
    volumes:
      - nova_log:/var/log/nova
    command: ["bash", "/opt/start.sh"]

volumes:
  nova_log:
    driver: local

networks:
  openstack-management-net:
    external: true
