---
version: "3"

services:

  glance:
    build: .
    container_name: openstack_glance
    ports:
      - "0.0.0.0:9292:9292"
    networks:
      - openstack-management-net
    external_links:
      - openstack_postgresql:openstack_postgresql
      - openstack_keystone:openstack_keystone
      - openstack_memcached:openstack_memcached
    volumes:
      - glance_log:/var/log/glance
      - glance_images:/var/lib/glance/images
    command: ["bash"]

volumes:
  glance_log:
    driver: local
  glance_images:
    driver: local

networks:
  openstack-management-net:
    external: true