---
  version: '2'

  services:
    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:5.6.2
      container_name: openstack_infra_elasticsearch
      environment:
        - "xpack.security.enabled=false"
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m -Xms1g -Xmx1g"
      volumes:
        - openstack_volume_elasticsearch:/usr/share/elasticsearch/data
      ports:
        - "0.0.0.0:9200:9200"
        - "0.0.0.0:9300:9300"
      networks:
        - openstack-management-net

  volumes:
    openstack_volume_elasticsearch:
      external: true

  networks:
    openstack-management-net:
      external: true