---
version: "2"

services:

  memcached:
    build: .
    container_name: openstack_memcached
    ports:
      - "11211:11211"
    networks:
      - openstack-management-net

networks:
  openstack-management-net:
    external: true