---

  version: "2"

  # starts 4 docker containers running minio server instances. Each
  # minio server's web interface will be accessible on the host at port
  # 9001 through 9004.
  services:
    minio:
      image: minio/minio
      container_name: openstack_minio
      ports:
        - "0.0.0.0:9001:9000"
      environment:
        MINIO_ACCESS_KEY: minio
        MINIO_SECRET_KEY: minio123
      volumes:
        - openstack_volume_minio:/data
        - openstack_volume_minio_config:/root/.minio
      command: ["bash", "/opt/start.sh", "&&", "server", "/data"]
      networks:
        - openstack-management-net

  volumes:
    openstack_volume_minio:
      external: true
    openstack_volume_minio_config:
      external: true

  networks:
    openstack-management-net:
      external: true