---
  version: "3"

  services:

    neutron:
      build: .
      container_name: openstack_neutron
      networks:
        - openstack-management-net
        - openstack-provider-net
      ports:
        - "0.0.0.0:9696:9696"
      volumes:
        - neutron_log:/var/log/neutron
        - /lib/modules:/lib/modules
        - /run/openvswitch/db.sock:/run/openvswitch/db.sock
      command: ["bash", "/opt/start.sh"]
      cap_add:
        - NET_ADMIN
        - SYS_MODULE

  volumes:
    neutron_log:
      driver: local

  networks:
    openstack-management-net:
      external: true
    openstack-provider-net:
      external: true
