---
  version: '3.1'

  services:

    mariadb:
      image: mariadb:10.3.4
      container_name: openstack_mariadb
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_USER: mysql
        MYSQL_PASS: secret
      ports:
        - "0.0.0.0:3306:3306"
      volumes:
        - openstack_volume_mariadb:/var/lib/mysql/
      networks:
        - openstack-management-net

  volumes:
    openstack_volume_mariadb:
      external: true

  networks:
    openstack-management-net:
      external: true