---
version: "2"

services:

  rabbitmq:
    build: .
    container_name: openstack_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - openstack-management-net

networks:
  openstack-management-net:
    external: true