---
  version: "3"

  services:

    neutron:
      build: .
      container_name: openstack_neutron
      networks:
        - openstack-management-net
      ports:
        - "0.0.0.0:9696:9696"
      external_links:
        - openstack_mariadb:openstack_mariadb
        - openstack_rabbitmq:openstack_rabbitmq
        - openstack_memcached:openstack_memcached
        - openstack_keystone:openstack_keystone
        - openstack_nova:openstack_nova
      volumes:
        - neutron_log:/var/log/neutron
      command: ["bash", "start.sh"]

  volumes:
    neutron_log:
      driver: local

  networks:
    openstack-management-net:
      external: true
