---
version: "3"

services:

  openstackclient:
    build: .
    container_name: openstack_clients
    networks:
      - openstack-management-net
      # - openstack-public-net
      # - openstack-private-net
    external_links:
      - openstack_keystone:openstack_keystone
    environment:
      - OS_PROJECT_DOMAIN_NAME=default
      - OS_USER_DOMAIN_NAME=default
      - OS_PROJECT_NAME=admin
      - OS_USERNAME=admin
      - OS_PASSWORD=secret
      - OS_AUTH_URL=http://openstack_keystone:35357/v3
      - OS_IDENTITY_API_VERSION=3
      - OS_IMAGE_API_VERSION=2

networks:
  openstack-management-net:
    external: true
  openstack-private-net:
    external: true
  openstack-public-net:
    external: true